### ISSUE TITLE
Allow to use a file for request data

### ISSUE THREAD

**Issue by mykevinjung** [ExpediaGroup/mittens#112]
**Describe the feature**

When we set the request data, currently we have to put the actual data in `requests.data` field in the yml file.  Instead of putting the actual data in the configuration, can we use a path to a file that contains the request data?

For instance, current config:
```
app-service:
  warmup:
    ...
    requests:
      - type: "grpc"
        method: "com.mycompany.Service/Method"
        data: '{\"name\":\"John\",\"age\":30,\"cars\":{\"car1\":\"Ford\",\"car2\":\"BMW\",\"car3\":\"Fiat\"}}'
```

proposed config
```
app-service:
  warmup:
    ...
    requests:
      - type: "grpc"
        method: "com.mycompany.Service/Method"
        data: "file:smoke-test/src/test/resources/mycar.json"
```

**Rational**

Request data is often big and putting the big data in yml-escaped format is error-prone.  Normally people have the request data file for test purpose especially for gRPC, but with the current limitation, people have to convert the content of the data file into a single line and escaped the data to fit into yml format, e.g. prepending `\` before every double-quotes, which is error-prone.

**Example Scenario**

Sample proposed config above.
